export const SYNC_BACKGROUND_SEARCH_QUERY_TAG = "SEARCH_TAG";
export const SYNC_BACKGROUND_SEARCH_QUERY_RESULT = "SEARCH_RESULTS_READY";
export const SYNC_SAVE_ANIMATION_TAG = "SYNC_SAVE_ANIMATION_TAG";
export const SYNC_REMOVE_ANIMATION_TAG = "SYNC_REMOVE_ANIMATION_TAG";
